"use client";

import React, { useState } from "react";
import { Download, Loader2 } from "lucide-react";
import jsPDF from "jspdf";
import { ResumeData } from "@/hooks/useResumeStore";

export default function ExportReportButton({ resume, filename }: { resume: ResumeData, filename?: string }) {
    const [isExporting, setIsExporting] = useState(false);

    const handleExport = async () => {
        setIsExporting(true);
        try {
            const doc = new jsPDF({
                orientation: "portrait",
                unit: "mm",
                format: "a4",
            });

            const targetFilename = filename || `${resume.name.replace(/\s+/g, "_")}_ATS_Report.pdf`;
            const pageWidth = doc.internal.pageSize.getWidth();
            const pageHeight = doc.internal.pageSize.getHeight();
            
            // Left/Right margin: 20mm
            const margin = 20;
            const printableWidth = pageWidth - 2 * margin; // 170mm
            let y = 25; // starting y position

            // Helper to handle page breaks
            const checkPageBreak = (neededHeight: number) => {
                if (y + neededHeight > pageHeight - 20) {
                    addPageFooter();
                    doc.addPage();
                    y = 25;
                    addPageHeader();
                }
            };

            const addPageHeader = () => {
                doc.setFont("helvetica", "normal");
                doc.setFontSize(8);
                doc.setTextColor(100, 100, 100);
                doc.text("RESUME ATS DIAGNOSTIC REPORT", margin, 15);
                doc.setDrawColor(200, 200, 200);
                doc.setLineWidth(0.2);
                doc.line(margin, 17, pageWidth - margin, 17);
            };

            const addPageFooter = () => {
                const totalPages = (doc as any).internal.pages.length - 1;
                doc.setFont("helvetica", "normal");
                doc.setFontSize(8);
                doc.setTextColor(120, 120, 120);
                doc.setDrawColor(220, 220, 220);
                doc.setLineWidth(0.2);
                doc.line(margin, pageHeight - 17, pageWidth - margin, pageHeight - 17);
                doc.text(
                    `Page ${totalPages}`,
                    pageWidth - margin - 15,
                    pageHeight - 12
                );
                doc.text("Generated by AI-powered Resume Analyzer", margin, pageHeight - 12);
            };

            const addHeading = (text: string) => {
                checkPageBreak(15);
                doc.setFont("helvetica", "bold");
                doc.setFontSize(12);
                doc.setTextColor(0, 0, 0);
                doc.text(text.toUpperCase(), margin, y);
                y += 5;
                doc.setDrawColor(180, 180, 180);
                doc.setLineWidth(0.3);
                doc.line(margin, y, pageWidth - margin, y);
                y += 7;
            };

            const addParagraph = (text: string, fontSize = 10, isBold = false, spacing = 5) => {
                doc.setFont("helvetica", isBold ? "bold" : "normal");
                doc.setFontSize(fontSize);
                doc.setTextColor(30, 30, 30);
                const lines: string[] = doc.splitTextToSize(text, printableWidth);
                
                for (const line of lines) {
                    checkPageBreak(5);
                    doc.text(line, margin, y);
                    y += (fontSize * 0.3527) + 1.2;
                }
                y += spacing;
            };

            const addBulletPoint = (text: string, fontSize = 10, spacing = 2) => {
                doc.setFont("helvetica", "normal");
                doc.setFontSize(fontSize);
                doc.setTextColor(30, 30, 30);
                const bulletChar = "• ";
                const indent = 5;
                
                const lines: string[] = doc.splitTextToSize(text, printableWidth - indent);
                
                checkPageBreak(5);
                // First line gets the bullet
                doc.text(bulletChar, margin, y);
                doc.text(lines[0], margin + indent, y);
                y += (fontSize * 0.3527) + 1.2;

                for (let i = 1; i < lines.length; i++) {
                    checkPageBreak(5);
                    doc.text(lines[i], margin + indent, y);
                    y += (fontSize * 0.3527) + 1.2;
                }
                y += spacing;
            };

            // First page initialization
            addPageHeader();

            // 1. Header Details
            doc.setFont("helvetica", "bold");
            doc.setFontSize(20);
            doc.setTextColor(0, 0, 0);
            doc.text("RESUME ANALYSIS REPORT", margin, y);
            y += 8;

            doc.setFont("helvetica", "normal");
            doc.setFontSize(10);
            doc.setTextColor(80, 80, 80);
            doc.text(`Candidate File: ${resume.name}`, margin, y);
            y += 5;
            doc.text(`Date of Analysis: ${resume.date}`, margin, y);
            y += 10;

            // 2. Score Metrics Banner (Text-based box)
            checkPageBreak(35);
            doc.setDrawColor(0, 0, 0);
            doc.setLineWidth(0.5);
            doc.rect(margin, y, printableWidth, 24);
            
            doc.setFont("helvetica", "bold");
            doc.setFontSize(11);
            doc.setTextColor(0, 0, 0);
            doc.text("ATS COMPLIANCE SCORE", margin + 10, y + 10);
            doc.text("SKILLS COMPATIBILITY MATCH", margin + 90, y + 10);

            doc.setFontSize(18);
            doc.text(`${resume.score}%`, margin + 10, y + 18);
            doc.text(`${resume.skillsMatch}%`, margin + 90, y + 18);
            y += 32;

            // 3. Executive Summary
            addHeading("Executive Summary");
            addParagraph(resume.summary || "No executive summary parsed.", 10, false, 8);

            // 4. Quick Metrics Gaps
            addHeading("Keyword & Competency Gaps");
            addParagraph(`Matched Keywords: ${resume.matchedKeywords}`, 10, true, 2);
            addParagraph(`Missing Keywords: ${resume.missingKeywords}`, 10, true, 8);

            // 5. Strengths
            if (resume.strengths && resume.strengths.length > 0) {
                addHeading("Compliance Strengths");
                resume.strengths.forEach((strength) => {
                    addBulletPoint(strength);
                });
                y += 6;
            }

            // 6. Areas for Improvement
            if (resume.weaknesses && resume.weaknesses.length > 0) {
                addHeading("Identified Vulnerabilities & Gaps");
                resume.weaknesses.forEach((weakness) => {
                    addBulletPoint(weakness);
                });
                y += 6;
            }

            // 7. Detailed Keywords Category lists
            const matchedList = resume.keywords
                .filter(k => k.category === "matched")
                .map(k => `${k.word} (${k.count}x)`);

            const missingList = resume.keywords
                .filter(k => k.category === "missing")
                .map(k => k.word);

            if (matchedList.length > 0) {
                addHeading("Identified & Matched Keywords");
                addParagraph(matchedList.join(", "), 10, false, 8);
            }

            if (missingList.length > 0) {
                addHeading("Recommended Keywords to Add");
                addParagraph(missingList.join(", "), 10, false, 8);
            }

            // 8. Recommended Skills
            if (resume.recommendedSkills && resume.recommendedSkills.length > 0) {
                addHeading("Recommended Skills & Certifications");
                addParagraph(resume.recommendedSkills.join(", "), 10, false, 8);
            }

            // 9. Suggested Roadmap
            if (resume.suggestedRoadmap && resume.suggestedRoadmap.length > 0) {
                addHeading("Upskilling Study Roadmap");
                resume.suggestedRoadmap.forEach((item) => {
                    checkPageBreak(18);
                    doc.setFont("helvetica", "bold");
                    doc.setFontSize(10);
                    doc.setTextColor(0, 0, 0);
                    doc.text(`Step ${item.step}: ${item.title} (${item.duration})`, margin, y);
                    y += 5;
                    addParagraph(item.description, 9.5, false, 2);
                    if (item.skills.length > 0) {
                        addParagraph(`Target Skills: ${item.skills.join(", ")}`, 9, true, 4);
                    }
                    y += 2;
                });
            }

            // Final page footer addition
            addPageFooter();

            // Save PDF file
            doc.save(targetFilename);
        } catch (error) {
            console.error("Export failed", error);
        } finally {
            setIsExporting(false);
        }
    };

    return (
        <button
            onClick={handleExport}
            disabled={isExporting}
            className="h-10 px-4 rounded-lg bg-secondary border border-border text-foreground hover:bg-accent text-xs font-semibold transition-all flex items-center gap-2 shadow-sm disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
        >
            {isExporting ? <Loader2 className="size-4 animate-spin" /> : <Download className="size-4" />}
            {isExporting ? "Generating PDF..." : "Export Report"}
        </button>
    );
}
